### ISSUE TITLE
Update to use both old and new JIRA URL patterns

### ISSUE THREAD

**Issue by DTrejo** [1debit/trufflehog-fp-analyzer#12]
https://github.com/1debit/trufflehog-fp-analyzer/blob/bd3ca7ef6739cf9f238c130c73419c7d7e78401a/rules.yaml#L5

**Comment by mazen160** [comment]
@DTrejo it seems this issue was missed, but I think we have updated the pattern to match both new and old patterns:
https://github.com/1debit/trufflehog-fp-analyzer/blob/master/rules.yaml#L5

Thank you!
